# appveyor.yml
image: macos

clone_folder: /tmp/src/github.com/shawn1m/overture

environment:
  GOPATH: /tmp/

stack: go 1.13

before_build:
  - "go version"
  - "ls -al"
  - "python3 ./build.py -build"

before_test:
  - go vet ./...

test_script:
  - go test ./...

artifacts:
  - path: 'overture-*.zip'
